---
- name: configure backend from config file
  hosts: terraform
  gather_facts: no
  tasks:
    - include_role: 
        name: terraform
        tasks_from: config_backend.yml
      when: backend_config == "true"
      
- name: deploy new project
  hosts: terraform
  gather_facts: no
  tasks:
    - include_role: 
        name: terraform
        tasks_from: deploy_project.yml
      when: new_project == "true"

- name: create tfplan dont execute
  hosts: terraform
  gather_facts: no
  tasks:
    - include_role: 
        name: terraform
        tasks_from: create_plan.yml
      when: plan_type == "create only"

- name: Apply from tfplan
  hosts: terraform
  gather_facts: no
  tasks:
    - include_role: 
        name: terraform
        tasks_from: apply_plan.yml
      when: plan_type == "apply only"

- name: Create and apply plan
  hosts: terraform
  gather_facts: no
  tasks:
    - include_role: 
        name: terraform
      when: plan_type == "create and apply"

# Commented this out since we set vars in create_plan. 
# however leaving this in to show we can set vars on the fly
# - name: Set vriables
#   hosts: terraform
#   gather_facts: no
#   tasks:
#     - include_role: 
#         name: terraform
#         tasks_from: update_terraform_vars.yml
#       when: update_vars_input == "true"