---
- name: test vars
  hosts: localhost
  tasks:
    - debug:
        msg: "state is {{state}} update_vars is {{update_vars_input}} project_path is {{project_path_input}} plan_file is {{plan_file_input}}"

# - name: create tfplan dont execute
#   hosts: terraform
#   tasks:
#     - include_role: 
#         name: terraform
#         tasks_from: create_plan.yml
#     when: state == "create only"

# - name: Apply from tfplan
#   hosts: terraform
#   tasks:
#     - include_role: 
#         name: terraform
#         tasks_from: apply_plan.yml
#     when: state = "apply only"

# - name: Create and apply plan
#   hosts: terraform
#   tasks:
#     - include_role: 
#         name: terraform
#     when: state = "apply and create"

# - name: Set vriables
#   hosts: terraform
#   tasks:
#     - include_role: 
#         name: terraform
#         tasks_form: update_terraform_vars.yml
#     when: update_vars == true