---
- name: Update backend using file
  community.general.terraform:
    project_path: "{{project_path_input}}"
    state: present
    force_init: true
    init_reconfigure: true
    backend_config_files:
      - "{{config_file_path}}"
