- name: 
  community.general.terraform:
    project_path: "{{project_path_input}}"
    variables: 
      ami_name: "{{ami_input}}"
      vpc_cidr_input: "{{vpc_cidr_block}}"
      subnet_cidr_input: "{{subnet_cidr_block}}"
  register: output